name = "All of Maeves"
author = "maeve"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "a2168b981b28b10e146377753aba6065fde9716e9934ca988cfb2554c76da1e9"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.230"
