name = "All of Maeves"
author = "maeve"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "7b600a873de8f12133f79380de49067024f2a26eef2087b398d590751a330904"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.230"
