name = "All of Maeves"
author = "maeve"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "9abc2009bca8702515f389d4c520c815fc5e1dc37ebcc81e9fd28f832bbb5934"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.230"
